abb_irb140:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller_1:
    type: velocity_controllers/JointPositionController
    joint: joint_1_1
    pid: {p: 5.0, i: 0.001, d: 0.0}

  joint2_position_controller_1:
    type: velocity_controllers/JointPositionController
    joint: joint_2_1
    pid: {p: 5.0, i: 0.001, d: 0.0}
  
  joint3_position_controller_1:
    type: velocity_controllers/JointPositionController
    joint: joint_3_1
    pid: {p: 5.0, i: 0.001, d: 0.0}

  joint4_position_controller_1:
    type: velocity_controllers/JointPositionController
    joint: joint_4_1
    pid: {p: 5.0, i: 0.001, d: 0.0}
  
  joint5_position_controller_1:
    type: velocity_controllers/JointPositionController
    joint: joint_5_1
    pid: {p: 5.0, i: 0.001, d: 0.0}

  joint6_position_controller_1:
    type: velocity_controllers/JointPositionController
    joint: joint_6_1
    pid: {p: 5.0, i: 0.001, d: 0.0}

  # Position Controllers ---------------------------------------
  joint1_position_controller_2:
    type: velocity_controllers/JointPositionController
    joint: joint_1_2
    pid: {p: 5.0, i: 0.001, d: 0.0}

  joint2_position_controller_2:
    type: velocity_controllers/JointPositionController
    joint: joint_2_2
    pid: {p: 5.0, i: 0.001, d: 0.0}
  
  joint3_position_controller_2:
    type: velocity_controllers/JointPositionController
    joint: joint_3_2
    pid: {p: 5.0, i: 0.001, d: 0.0}

  joint4_position_controller_2:
    type: velocity_controllers/JointPositionController
    joint: joint_4_2
    pid: {p: 5.0, i: 0.001, d: 0.0}
  
  joint5_position_controller_2:
    type: velocity_controllers/JointPositionController
    joint: joint_5_2
    pid: {p: 5.0, i: 0.001, d: 0.0}

  joint6_position_controller_2:
    type: velocity_controllers/JointPositionController
    joint: joint_6_2
    pid: {p: 5.0, i: 0.001, d: 0.0}
